spring:
  datasource:
    url: jdbc:mysql://192.168.1.51:30306/nuc-mysql?createDatabaseIfNotExist=true
    username: root
    password: 12345Wq!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true